import socket
sock = socket.socket()
sock.connect(('127.0.0.1',1234))
print("Connection done")
print("SERVER:", end="")
print(sock.recv(1024).decode())
print("CLIENT:", end="")
t = input()
sock.send(t.encode())
print("SERVER:",end="")
print(sock.recv(1024).decode())
print("CLIENT:",end="")
t1=(input())
sock.send(t1.encode())
print("SERVER:",end="")
print(sock.recv(1024).decode())
print("CLIENT:",end="")
t2 =(input())
sock.send(t2.encode())
print("SERVER:",end="")
print(sock.recv(1024).decode())
